runtime: python311
entrypoint: gunicorn aorbo_website.wsgi --bind=0.0.0.0:$PORT

env_variables:
  DJANGO_SETTINGS_MODULE: "aorbo_website.settings"
  SECRET_KEY: "your-secret-key"
  DEBUG: "False"

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
